# .gitleaks.toml
title = "GitLeaks Configuration"

[allowlist]
description = "Whitelist de faux positifs ou secrets autorisés"
# Exemple : fichiers spécifiques ou valeurs regex autorisées
files = []
paths = []
regexes = [
  '''(?i)(example|dummy)_?(key|token|password)''',
]

[rule]
description = "Règles personnalisées"

[[rules]]
id = "generic-api-key"
description = "Détection de clés API génériques"
regex = '''(?i)(api[_-]?key|access[_-]?key|secret[_-]?key)[\'"\s:=]+[0-9a-zA-Z]{16,64}'''
tags = ["key", "api", "generic"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(secret|private)?(.{0,20})?['\"][0-9a-zA-Z\/+=]{40}['\"]'''
tags = ["key", "aws"]

[[rules]]
id = "password-in-code"
description = "Mots de passe codés en dur"
regex = '''(?i)(password|pwd|pass)[\'"\s:=]+[^\s\'"]+'''
tags = ["password", "credential"]

[[rules]]
id = "private-key"
description = "Clé privée"
regex = '''-----BEGIN(?: RSA)? PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

