name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build l’image Docker
        run: docker build -t devsecure-api .

      - name: Trivy - Scan de l’image Docker
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: devsecure-api
            format: table
            exit-code: 1
            ignore-unfixed: true

      - name: Snyk - Analyse de sécurité
        uses: snyk/actions/docker@master
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            image: devsecure-api
            args: --file=Dockerfile

      - name: GitLeaks - Scan des secrets
        uses: gitleaks/gitleaks-action@v2
        with:
            args: detect --source . --verbose --redact --exit-code 1 
          
        
